{% set name = "rbeast" %}
{% set version = "0.1.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Rbeast-{{ version }}.tar.gz
  sha256: b616fb54de460e7cedd1709047d1cbb9528d2571ddd097074c36f1571e8c4ee4

build:
  skip: true  # [py<37 or win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools >=61
    - wheel
    - numpy >=1.17.3
    - pip
  run:
    - python
    - matplotlib-base >=2.2.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - Rbeast
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zhaokg/Rbeast
  summary: Bayesian changepoint detection and time series decomposition
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
