{% set name = "rbeast" %}
{% set version = "0.1.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Rbeast-{{ version }}.tar.gz
  sha256: 60c1d7f02588155f92326663c355e04e5875634003133a258e7a0f10a43f719a

build:
  skip: true  # [py<37 or win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools >=61
    - wheel
    - numpy >=1.17.3
    - pip
  run:
    - python
    - matplotlib-base >=2.2.0

test:
  imports:
    - Rbeast
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zhaokg/Rbeast
  summary: Bayesian changepoint detection and time series decomposition
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
