{% set name = "rbeast" %}
{% set version = "0.1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Rbeast-{{ version }}.tar.gz
  sha256: 75103ef904d36f3fd6edcba27666d97bf308f117d79def7ab4138d5a7fe93fc7

build:
  skip: true  # [py<36 or win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools >=61
    - wheel
    - numpy >=1.17.3
    - pip
  run:
    - python
    - matplotlib-base >=2.2.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - Rbeast
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zhaokg/Rbeast
  summary: Bayesian changepoint detection and time series decomposition
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
